// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = "https://oncmszfundzwjowtlpnw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9uY21zemZ1bmR6d2pvd3RscG53Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0ODIyMTksImV4cCI6MjA3MDA1ODIxOX0.iza8sai2me7OSYAIN2uuct1Qw127gxo_1iFAFh23Pio";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
    SUPABASE_URL,
    SUPABASE_PUBLISHABLE_KEY,
    {
        auth: {
            persistSession: true,
            autoRefreshToken: true,
        },
    }
);
